### ISSUE TITLE
Add support for JSON-RPC

### ISSUE THREAD

**Issue by monisallam** [fooelisa/pyiosxr#11]
Hello, my name is Moni Sallam, and I am on a new team at Cisco, whose sole purpose is to contribute to open source projects. `pyiosxr` and `NAPALM` are two repos that have caught our interest. 

Cisco is moving towards using json-rpc as a first class interface for our products. I would like to add support for `JSON-RPC` into `pyiosxr`, and would like to get your feedback. 

`JSON-RPC` is a simpler protocol than `XML-RPC`, and provides a structured return output, as opposed to CLI based screen scraping.

[Here](http://www.simple-is-better.org/rpc/#why-json-rpc) is some material if you would like to explore this further...

**Comment by dbarrosop** [comment]
That's really awesome! Is there any Cisco documentation, VMs or anything
you can share to help testing and developing?

**Comment by jasonwalsh** [comment]
Hey @dbarrosop,

We can certainly provide documentation for programability of Cisco devices using the `JSON-RPC` protocol. I'll be sure to compile a list of documentation and send it to you.

Also, we are currently working on a high-level abstraction layer for both `XML-RPC` and `JSON-RPC` that will essentially serve as factory for various devices.

**Comment by fooelisa** [comment]
Sounds fantastic, please keep us posted and let us know if there is anything we can do to help!

**Comment by jejenone** [comment]
@rightlag what about RestConf ?
What is Cisco's strategy regarding these protocols ? Are you going to support both XML Agent and Netconf in IOS-XR or is one of them going to be deprecated at some point ?

**Comment by fooelisa** [comment]
Closing this thread, please let us know when you have further information on this! Thanks!

**Comment by jejenone** [comment]
FWIW, this is available in IOS-XR 6.0 - which is still not available on ASR
