### ISSUE TITLE
xml requests

### ISSUE THREAD

**Issue by runborg** [fooelisa/pyiosxr#20]
Hi!

Is there any reason why xml requests are hand crafted as text instead of using ElementTree to craft them?   

f.eks when commiting data: 

``` python
In [20]: tostring(SubElement(Element('Request'), "Commit", Replace="False", Label="", Comment="", Confirmed=""))

Out[20]: <Commit Replace="true" Label=""' Comment="" Confirmed=""/>`
```

all paramters could also be added via a dict instead of kwargs. this work great on short xml statements, but is more "texty" when multiple commands needs to be passed:

``` python
root = Element('Request')
root.append(Element('Unlock'))
rollback = SubElement(root, "Rollback")
prev = SubElement(rollback, "Previous")
prev.text = "1"
root.append(Element('Lock'))
''.join(map(tostring, root.getchildren()))
Out[62]: '<Lock /><Rollback><Previous>1</Previous></Rollback><unLock />'
```

iv'e ignored the root object becouse thats added elsewhere in the code. 

is this something that have been discussed ?

**Comment by fooelisa** [comment]
No reason, originally it was just passing a few requests, didn't seem necessary to implement any more complex build procedure for it. All yours if you want to give it a shot!

**Comment by mirceaulinic** [comment]
@runborg I don't see any gain by transforming from text to XML object and back to text.
I am going to close this ticket as the solution proposed seems overly complicated.
There are many improvements we can apply to this library, but this is not one of them IMO.
