### ISSUE TITLE
Error handling on lack of XML support on router

### ISSUE THREAD

**Issue by WackoRobie** [fooelisa/pyiosxr#4]
Fails on .open() when xml mode has not been enabled on remote device, but does not give any indication of the error being beyond opening the connection.

**Comment by WackoRobie** [comment]
Started working on adding in some type of error catching and reporting. Suggestions would be helpful.

**Comment by dbarrosop** [comment]
Maybe just returning what is in the stdin and the stdout in case of an exception would be good enough to have an idea on what the actual problem is.

**Comment by fooelisa** [comment]
added a specific error for this in version 0.10
